# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    # runs-on: ubuntu-latest (need .sh scripts)

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: ./eng/build.ps1 -restore
    - name: Build
      run: ./eng/build.ps1 -build -config Debug
    - name: Test
      run: ./eng/build.ps1 -test

